 <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800&amp;subset=cyrillic-ext" rel="stylesheet">
<link rel="stylesheet" href="/libs/normalize.css/normalize.css">
<link rel="stylesheet" href="/libs/jquery-nice-select/css/nice-select.css">
<link rel="stylesheet" href="/libs/slick-carousel/slick/slick.css">
<link rel="stylesheet" href="/libs/multi-select/jquery.multiselect.css">
<link rel="stylesheet" href="/libs/fancybox/dist/jquery.fancybox.min.css">
<link rel="stylesheet" href="/libs/air-datepicker/dist/css/datepicker.min.css">
<link rel="stylesheet" href="/libs/scrollbar/jquery.scrollbar.css">
<link rel="stylesheet" href="/css/style.css">
<link rel="stylesheet" href="/css/site.css">